name: mpc_ground_repository
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  reqres_api:
    path: ../reqres_api

dev_dependencies:
  build_runner: ^2.3.0
  coverage: ^1.6.2
  freezed: ^2.2.0
  json_serializable: ^6.5.4
  mocktail: ^0.3.0
  test: ^1.21.4
  very_good_analysis: ^3.0.2
  