targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - implicit_dynamic_parameter
      freezed:
        options:
          copy_with: false
          equal: false
          to_json: false
      json_serializable:
        options:
          field_rename: snake
          checked: true
