name: reqres_api
description: A new Flutter package project.
version: 0.0.1
homepage: null

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  freezed_annotation: ^2.2.0
  http: ^0.13.5
  json_annotation: ^4.7.0

dev_dependencies:
  build_runner: ^2.3.0
  freezed: ^2.2.0
  json_serializable: ^6.5.4
  mocktail: ^0.3.0
  test: ^1.21.4
  very_good_analysis: ^3.0.2
